### ISSUE TITLE
React Native color format support

### ISSUE THREAD

**Issue by krachtstefan** [radix-ui/colors#15]
Do you have any plans to support React Native color formats? When using it inside my project, I get the following error:

```
Invariant Violation: Invalid prop `backgroundColor` supplied to `StyleSheet generated`: hsl(136 50.0% 98.9%)
Valid color formats are
  - '#f0f' (#rgb)
  - '#f0fc' (#rgba)
  - '#ff00ff' (#rrggbb)
  - '#ff00ff00' (#rrggbbaa)
  - 'rgb(255, 255, 255)'
  - 'rgba(255, 255, 255, 1.0)'
  - 'hsl(360, 100%, 100%)'
  - 'hsla(360, 100%, 100%, 1.0)'
  - 'transparent'
  - 'red'
  - 0xff00ff00 (0xrrggbbaa)
```

I could fix it in my code with a simple helper function that converts `hsl(136 50.0% 98.9%)` to `hsl(136, 50.0%, 98.9%)`, but I just wondered If you might already have a (planned) solution.

Thanks for creating and maintaining this repository!

**Comment by lucasmotta** [comment]
Just ran into the same issue when trying to use it with React Native. 

@colmtuite @vladmoroz I assume there's no drawback to use the hsl with the comma formatting, right? Do you mind if I send a PR with this change?
