### ISSUE TITLE
Wrong Color Exported as SVG for mauveDarkA 

### ISSUE THREAD

**Issue by pratiksharm** [radix-ui/colors#21]
<img width="838" alt="Screenshot 2022-04-07 at 10 49 44 AM" src="https://user-images.githubusercontent.com/29139349/162125751-a75d0cdc-6751-4d5f-a52c-49b68468c389.png">

When i copy the colours as SVG. They are not exported with correct colour palette.
<img width="813" alt="Screenshot 2022-04-07 at 10 51 12 AM" src="https://user-images.githubusercontent.com/29139349/162126113-63b53f3b-9879-4e1c-8227-0fa72c8d1769.png">

Here is the wrong color palette. That it exports 

<img width="540" alt="Screenshot 2022-04-07 at 10 51 44 AM" src="https://user-images.githubusercontent.com/29139349/162126161-318cd628-9bf4-4d23-b802-2642bee984ea.png">

**Comment by colmtuite** [comment]
Set the frame background to MauveDark step 1.
