### ISSUE TITLE
Usage with tailwind opacity modifier

### ISSUE THREAD

**Issue by nichtsam** [radix-ui/colors#33]
Is there a way to use `@radix-ui/colors` with `tailwind`'s opacity modifier?
I know I could just copy the content and modify it, but I would prefer to keep it sync and simple.

https://tailwindcss.com/docs/customizing-colors#using-css-variables

**Comment by garand** [comment]
Check out this plugin! https://github.com/brattonross/windy-radix-palette

There's an issue with v3 colors in P3 right now, but if you pin to @radix-ui/colors@2 and windy-radix-palette@0.6.1 then you'll be good for now.
